# Generated by Django 4.2.27 on 2026-02-11 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=50, verbose_name='Exam Section')),
                ('system', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('general', 'General English')], max_length=50, verbose_name='Exam System')),
                ('exam_time_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(36000)], verbose_name='Exam Time (seconds)')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='ExamPack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('general', 'General English')], max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_pack',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Feedback Description')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Attempt Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('graded', 'Graded')], default='draft', max_length=20, verbose_name='Status')),
                ('response_text', models.TextField(blank=True, null=True, verbose_name='Text Response')),
                ('response_voice_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Voice File Path')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to='team3.exam', verbose_name='Exam')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_exams', to='team3.feedback', verbose_name='Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exams', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Exam',
                'verbose_name_plural': 'User Exams',
                'db_table': 'user_exam',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Question Number')),
                ('description', models.TextField(verbose_name='Question Description')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='team3.exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_deleted'], name='feedback_is_dele_05ede1_idx'),
        ),
        migrations.AddIndex(
            model_name='exampack',
            index=models.Index(fields=['system'], name='exam_pack_system_af5f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='exampack',
            index=models.Index(fields=['is_deleted'], name='exam_pack_is_dele_6bb2f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampack',
            constraint=models.UniqueConstraint(fields=('system', 'title', 'is_deleted'), name='uq_exam_pack_system_title_activeflag'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='team3.exampack', verbose_name='Exam Pack'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['user', 'exam'], name='user_exam_user_id_87830a_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['status'], name='ix_user_exam_status'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['is_deleted'], name='user_exam_is_dele_3bbf0d_idx'),
        ),
        migrations.AddIndex(
            model_name='userexam',
            index=models.Index(fields=['created_at'], name='user_exam_created_24a09b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userexam',
            constraint=models.UniqueConstraint(fields=('user', 'exam', 'attempt_no', 'is_deleted'), name='uq_user_exam_attempt_activeflag'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'number'], name='question_exam_id_77698e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_deleted'], name='question_is_dele_afcec5_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'number', 'is_deleted'), name='uq_question_exam_number_activeflag'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['pack', 'section'], name='exam_pack_id_c21f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['section', 'system'], name='exam_section_3c1be6_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_deleted'], name='exam_is_dele_9da46b_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('pack', 'section', 'is_deleted'), name='uq_exam_pack_section_activeflag'),
        ),
    ]
